presupuesto_listado:
    pattern:  /{page}
    defaults: { _controller: PresupuestoBundle:Presupuesto:listado, page: 1 }
    requirements:
        page: \d+
    
manosdeobra_listado:
    pattern:  /manosdeobra/{page}
    defaults: { _controller: PresupuestoBundle:ManoDeObra:listado, page: 1 }
    requirements:
        page: \d+
manosdeobra_agregar:
    pattern:  /manosdeobra/agregar
    defaults: { _controller: PresupuestoBundle:ManoDeObra:agregar }
