presupuesto_listado:
    pattern:  /{page}
    defaults: { _controller: PresupuestoBundle:Presupuesto:listado, page: 1 }
    requirements:
        page: \d+
        
presupuesto_edicion:
    pattern:  /presupuesto/{id}
    defaults: 
        _controller: PresupuestoBundle:Presupuesto:edicion
        id: null
    requirements:
        id: \d+
        
presupuesto_export:
    pattern:  /presupuesto/{id}.xls
    defaults: 
        _controller: PresupuestoBundle:Presupuesto:export
    requirements:
        id: \d+
    
manosdeobra_listado:
    pattern:  /manosdeobra/{page}/{description}
    defaults:
        _controller: PresupuestoBundle:ManoDeObra:listado
        page: 1
        description: 
    requirements:
        page: \d+
        
manosdeobra_agregar:
    pattern:  /manosdeobra/agregar
    defaults: { _controller: PresupuestoBundle:ManoDeObra:agregar }
    
manosdeobra_editar:
    pattern:  /manosdeobra/editar/{id}
    defaults: { _controller: PresupuestoBundle:ManoDeObra:editar }
    requirements:
        id: \d+

manosdeobra_all_modal:
    pattern:  /manosdeobra/todas
    defaults: { _controller: PresupuestoBundle:ManoDeObra:getAll }
manosdeobra_all_json:
    pattern:  /manosdeobra/json
    defaults: { _controller: PresupuestoBundle:ManoDeObra:json }