parameters:
#    presupuesto.example.class: K2\PresupuestoBundle\Example

services:
#    presupuesto.example:
#        class: %presupuesto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    k2_view_selector:
        class: K2\PresupuestoBundle\Service\ViewSelector
        arguments: 
            - "@service_container"
            
    k2_twig_extensions:
        class: K2\PresupuestoBundle\Twig\PresupuestoExtension
        tags:
          - {name: twig.extension}
          
    presupuesto.manodeobra_manager:
        class: K2\PresupuestoBundle\Model\ManoDeObraManager
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - 'PresupuestoBundle:ManosDeObra'
          
    presupuesto.manager:
        class: K2\PresupuestoBundle\Model\PresupuestoManager
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - 'PresupuestoBundle:Presupuestos'

    presupuesto.form:
        class: K2\PresupuestoBundle\Form\PresupuestoForm
        tags:
          - {name: form.type, alias: presupuesto}
        arguments:
            - @doctrine.orm.entity_manager
            - @jms_serializer
          