parameters:
#    presupuesto.example.class: K2\PresupuestoBundle\Example

services:
#    presupuesto.example:
#        class: %presupuesto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    k2_view_selector:
        class: K2\PresupuestoBundle\Service\ViewSelector
        arguments: 
            - "@service_container"
